---
title: "COVID-19 in Luxembourg - Dashboard made with Open Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(xts)
library(dygraphs)
library(readxl)

main_categories <- c("Covid-19 midterm projection for continued Lockdown",
                     "Covid-19 midterm projection for a general exit on May 4th",
                     "Covid-19 midterm projection for construction worker release on April 20th",
                     "Covid-19 midterm projection for constructino worker release with testing and 25% efficent backtracing",
                     "Covid-19 midterm projection for constructino worker release with testing and 25% efficent backtracing")

lockdown_continued <- read.csv("https://download.data.public.lu/resources/covid-19-midterm-projection-for-continued-lockdown/20200424-090839/simulation-lockdown-continued.csv") %>% 
    mutate(dataset = "lockdown_continued")

general_ext <- read.csv("https://download.data.public.lu/resources/covid-19-midterm-projection-for-a-general-exit-on-may-4th/20200424-091111/simulation-general-exit-4may.csv") %>% 
    mutate(dataset = "general_ext")

workers_no_test <- read.csv("https://download.data.public.lu/resources/covid-19-midterm-projection-for-construction-worker-release-on-april-20th/20200424-091408/simulation-construction-workers20apr-no-test-no-trace.csv") %>% 
    mutate(dataset = "workers_no_test")

workers_25 <- read.csv("https://download.data.public.lu/resources/covid-19-midterm-projection-for-construction-worker-release-on-april-20th-with-testing-and-back-tracing/20200424-091607/simulation-construction-workers20apr-tracing25.csv") %>% 
    mutate(dataset = "workers_25")

workers_50 <- read.csv("https://download.data.public.lu/resources/covid-19-midterm-projection-for-construction-worker-release-on-april-20th-with-testing/20200424-091730/simulation-construction-workers20apr-tracing50.csv") %>% 
    mutate(dataset = "workers_50")

full_data <- bind_rows(
    list(lockdown_continued, general_ext, workers_no_test, workers_25, workers_50)
)


temp_xlsx <- tempfile()

download.file("https://data.public.lu/fr/datasets/r/bad0c25e-2397-4739-9916-1f9d60625f03", temp_xlsx)

covid_sante <- read_xlsx(temp_xlsx)
```

Simulation results from uni.lu
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

selectInput(inputId = "datasetName", 
            label = "Choose a dataset", 
            choices = unique(full_data$dataset))

selectInput(inputId = "seriesName",
            label = "Choose one series",
            choices = c("ICU.occupancy", "Total.cumulative.cases", "Number.of.deaths"),
            multiple = FALSE, selected = c("Total.cumulative.cases"))
```

Open data provided by the University of Luxembourg. This data shows simulations of different exit
scenarios. I am not responsible for the results; this app merely shows the data that was simulated by a 
research team of the university. Caution must be taken when interpreting results.

Source: https://data.public.lu/fr/organizations/university-of-luxembourg-1/

Layout based on https://jjallaire.shinyapps.io/shiny-biclust/

Row
-----------------------------------------------------------------------

### Simulation results
    
```{r}
dfInput <- reactive({
        filtered_data <- full_data %>% 
          filter(dataset == input$datasetName) %>% 
            select(Date, starts_with(input$seriesName))
        
        xts(filtered_data[, -1], order.by = as.Date(filtered_data[, 1], "%d/%m/%Y"))
    })

renderDygraph({
    df <- dfInput()
    dygraph(df) %>% 
         dyRangeSelector(dateWindow = c(head(df$Date, 1), tail(df$Date, 1)))
})
```

Min Health data 
=====================================  

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(inputId = "seriesName_sante",
            label = "Choose one or more series",
            choices = colnames(covid_sante)[-which(colnames(covid_sante) == "Date")],
            multiple = TRUE, selected = c("Total patients COVID ayant quitté l'hôpital"))

```

Open data provided by the Ministry of Health, Luxembourg.
This app merely shows the data made available by the ministry. No transformation is made on the data.

Source: https://data.public.lu/fr/datasets/donnees-covid19/

Row
-----------------------------------------------------------------------

### Number of patients, patients admitted in intensive care, COVID tests and deaths
    
```{r}

#shinipsum::random_dygraph()
dfInput_sante <- reactive({
        filtered_data <- covid_sante %>% 
            mutate(Date = as.Date(Date)) %>% 
            select(Date, input$seriesName_sante)
        
        xts(filtered_data[, -1], order.by = filtered_data$Date)
    })

renderDygraph({
    df <- dfInput_sante()
    dygraph(df) %>% 
         dyRangeSelector(dateWindow = c(head(df$Date, 1), tail(df$Date, 1)))
})
```
